import { z } from 'zod';

/**
 * How an entity's identity is assigned.
 *
 * `slug`         a name a person chose, once — Plan, Story, Sprint.
 * `natural-key`  whatever the source calls it — Branch, PR, Release, Issue,
 *                Build, Worktree.
 * `minted`       composed or generated by Plot — Agent, Slice.
 */
export const IdentityKindSchema = z.enum(['slug', 'natural-key', 'minted']);
export type IdentityKind = z.infer<typeof IdentityKindSchema>;

/**
 * How an identity of each kind fails.
 *
 * @param kind - the kind of identity.
 * @returns the failure mode that kind is prone to.
 */
export const identityFailureMode = (kind: IdentityKind): string => {
  switch (kind) {
    case 'slug':
      return 'collision';
    case 'natural-key':
      return 'the source lying';
    case 'minted':
      return 'nobody minting';
  }
};

/**
 * Where an entity's truth lives.
 *
 * `stated`    written in a file — Plan, Story, Sprint.
 * `derived`   computed from local facts — Slice, Branch, Release, Agent,
 *             Worktree, Issue.
 * `foreign`   held by an external surface — PR, Build.
 * `measured`  taken as a reading — Machine.
 */
export const StateSourceSchema = z.enum(['stated', 'derived', 'foreign', 'measured']);
export type StateSource = z.infer<typeof StateSourceSchema>;

/**
 * How state from each source goes wrong.
 *
 * @param source - where the state came from.
 * @returns the failure mode that source is prone to.
 */
export const stateFailureMode = (source: StateSource): string => {
  switch (source) {
    case 'stated':
      return 'being wrong';
    case 'derived':
      return 'staleness';
    case 'foreign':
      return 'the surface disagreeing';
    case 'measured':
      return 'decaying instantly';
  }
};

/**
 * A reading whose value is only true at the moment it was taken.
 *
 * Carried by measured state, where the value decays the instant it is read.
 *
 * @typeParam T - the value read.
 */
export interface Reading<T> {
  /** What was read. */
  value: T;
  /** When it was read, as epoch milliseconds. */
  measuredAt: number;
}

/**
 * Stamps a value as a reading taken at a given moment.
 *
 * The clock is a parameter because the domain may not reach one: a caller
 * supplies the time from the `Clock` port.
 *
 * @param value - what was read.
 * @param measuredAt - when it was read, as epoch milliseconds.
 * @returns the value paired with its measurement time.
 */
export const reading = <T>(value: T, measuredAt: number): Reading<T> => ({ value, measuredAt });

/**
 * How long ago a reading was taken.
 *
 * @param sample - the reading to age.
 * @param now - the current time, as epoch milliseconds.
 * @returns the elapsed milliseconds, never negative.
 */
export const readingAge = <T>(sample: Reading<T>, now: number): number =>
  Math.max(0, now - sample.measuredAt);
