#!/usr/bin/env node
var p=e=>`${e.label}: <${e.positions.join("|")}>`,c=(e,n,r)=>{if(n===null)return{read:"empty",lens:e,why:"wrote no file"};if(n.trim()==="")return{read:"empty",lens:e,why:"wrote an empty file"};let t=r.label.toLowerCase(),s=n.split(`
`).map(i=>i.trim()).filter(i=>i.toLowerCase().startsWith(`${t}:`)).map(i=>i.slice(r.label.length+1).trim());if(s.length===0)return{read:"uncommitted",lens:e,why:`no '${r.label}:' line \u2014 ${p(r)}`};let o=s.map(i=>{let[l]=i.split(/\s/);return r.positions.find(m=>m.toLowerCase()===l.toLowerCase())});if(o.some(i=>i===void 0))return{read:"uncommitted",lens:e,why:`'${s[o.findIndex(i=>i===void 0)]}' is not one of ${r.positions.join(", ")}`};let a=[...new Set(o)];return a.length>1?{read:"uncommitted",lens:e,why:`claims both ${a.join(" and ")}`}:{read:"committed",lens:e,position:a[0]}},u=e=>{if(e.length===0)return{panel:"refused",refusals:[{read:"empty",lens:"",why:"the panel had no jurors"}]};let n=e.filter(o=>o.read!=="committed");if(n.length>0)return{panel:"refused",refusals:n};let r=e,t={};for(let o of r)(t[o.position]??=[]).push(o.lens);let s=Object.keys(t);return s.length===1?{panel:"unanimous",position:s[0],lenses:t[s[0]]}:{panel:"divided",positions:t}};import{realpathSync as g}from"node:fs";import{pathToFileURL as f}from"node:url";var d={ok:0,usage:2,refused:3},h=(e,n,r)=>{let t=c(e,r,n);return t.read==="committed"?`committed	${t.lens}	${t.position}
`:`${t.read}	${t.lens}	${t.why}
`},y=e=>e.split(`
`).filter(n=>n!=="").map((n,r)=>{let[t,s,o]=n.split("	");if(s===void 0||o===void 0)throw new Error(`line ${r+1}: expected '<read>\\t<lens>\\t<detail>', got '${n}'`);switch(t){case"committed":return{read:t,lens:s,position:o};case"uncommitted":case"empty":return{read:t,lens:s,why:o};default:throw new Error(`line ${r+1}: '${t}' is not committed|uncommitted|empty`)}}),$=e=>{let n=u(y(e));switch(n.panel){case"refused":return`refused	${n.refusals.map(r=>`${r.lens}=${r.read}`).join(",")}
`;case"unanimous":return`unanimous	${n.position}	${n.lenses.join(",")}
`;case"divided":return`divided	${Object.entries(n.positions).map(([r,t])=>`${r}=${t.join(",")}`).join("	")}
`}},w=(e,n,r=t=>process.stdout.write(t))=>{let[t]=e;try{if(t==="reconcile"){let s=$(n);return r(s),s.startsWith("refused	")?d.refused:d.ok}if(t==="check"){let[,s,o,a]=e;if(!s||!o||!a)return process.stderr.write(`plot-panel: usage: plot-panel.mjs check <label> <a,b,c> <lens> < juror.md
`),d.usage;let i={label:s,positions:o.split(",")},l=h(a,i,n);return l.startsWith("committed	")?(r(l),d.ok):(process.stderr.write(`plot-panel: ${a} must write '${p(i)}'
`),r(l),d.refused)}return process.stderr.write(`plot-panel: usage: plot-panel.mjs check|reconcile ...
`),d.usage}catch(s){return process.stderr.write(`plot-panel: ${s.message}
`),d.usage}};if(process.argv[1]&&import.meta.url===f(g(process.argv[1])).href){let e=[];for await(let n of process.stdin)e.push(n);process.exit(w(process.argv.slice(2),Buffer.concat(e).toString("utf8")))}export{d as EXIT,h as check,y as readingsFrom,$ as reconcile,w as run};
