#!/usr/bin/env node
var c=n=>`${n.label}: <${n.positions.join("|")}>`,u=(n,t,r)=>{if(t===null)return{read:"empty",lens:n,why:"wrote no file"};if(t.trim()==="")return{read:"empty",lens:n,why:"wrote an empty file"};let e=r.label.toLowerCase(),s=t.split(`
`).map(o=>o.trim()).filter(o=>o.toLowerCase().startsWith(`${e}:`)).map(o=>o.slice(r.label.length+1).trim());if(s.length===0)return{read:"uncommitted",lens:n,why:`no '${r.label}:' line \u2014 ${c(r)}`};let i=s.map(o=>{let[p]=o.split(/\s/);return r.positions.find(l=>l.toLowerCase()===p.toLowerCase())});if(i.some(o=>o===void 0))return{read:"uncommitted",lens:n,why:`'${s[i.findIndex(o=>o===void 0)]}' is not one of ${r.positions.join(", ")}`};let d=[...new Set(i)];return d.length>1?{read:"uncommitted",lens:n,why:`claims both ${d.join(" and ")}`}:{read:"committed",lens:n,position:d[0]}},m=n=>{if(n.length===0)return{panel:"refused",refusals:[{read:"empty",lens:"",why:"the panel had no jurors"}]};let t=n.filter(i=>i.read!=="committed");if(t.length>0)return{panel:"refused",refusals:t};let r=n,e={};for(let i of r)(e[i.position]??=[]).push(i.lens);let s=Object.keys(e);return s.length===1?{panel:"unanimous",position:s[0],lenses:e[s[0]]}:{panel:"divided",positions:e}};import{realpathSync as g}from"node:fs";import{pathToFileURL as f}from"node:url";var a={ok:0,usage:2,refused:3},h=(n,t,r)=>{let e=u(n,r,t);return e.read==="committed"?`committed	${e.lens}	${e.position}
`:`${e.read}	${e.lens}	${e.why}
`},y=n=>n.split(`
`).filter(t=>t!=="").map((t,r)=>{let[e,s,i]=t.split("	");if(s===void 0||i===void 0)throw new Error(`line ${r+1}: expected '<read>\\t<lens>\\t<detail>', got '${t}'`);switch(e){case"committed":return{read:e,lens:s,position:i};case"uncommitted":case"empty":return{read:e,lens:s,why:i};default:throw new Error(`line ${r+1}: '${e}' is not committed|uncommitted|empty`)}}),w=n=>{let t=m(y(n));switch(t.panel){case"refused":return`refused	${t.refusals.map(r=>`${r.lens}=${r.read}`).join(",")}
`;case"unanimous":return`unanimous	${t.position}	${t.lenses.join(",")}
`;case"divided":return`divided	${Object.entries(t.positions).map(([r,e])=>`${r}=${e.join(",")}`).join("	")}
`}},$=n=>{let t=n.split(","),r=t.map(e=>e.trim()).join(",");if(t.some(e=>e.includes("|")))return`positions are separated by ',', not '|' \u2014 write '${n.split(/[,|]/).map(s=>s.trim()).filter(s=>s!=="").join(",")}'`;if(t.some(e=>e!==e.trim()))return`a position carries surrounding whitespace \u2014 write '${r}'`;if(t.some(e=>e===""))return"a position is empty \u2014 write every position between the commas";if(t.length<2)return`a commitment needs at least two positions \u2014 write '<a,b,c>', given '${n}'`},b=(n,t,r=e=>process.stdout.write(e))=>{let[e]=n;try{if(e==="reconcile"){let s=w(t);return r(s),s.startsWith("refused	")?a.refused:a.ok}if(e==="check"){let[,s,i,d]=n;if(!s||!i||!d)return process.stderr.write(`plot-panel: usage: plot-panel.mjs check <label> <a,b,c> <lens> < juror.md
`),a.usage;let o=$(i);if(o)return process.stderr.write(`plot-panel: ${o}
`),a.usage;let p={label:s,positions:i.split(",")},l=h(d,p,t);return l.startsWith("committed	")?(r(l),a.ok):(process.stderr.write(`plot-panel: ${d} must write '${c(p)}'
`),r(l),a.refused)}return process.stderr.write(`plot-panel: usage: plot-panel.mjs check|reconcile ...
`),a.usage}catch(s){return process.stderr.write(`plot-panel: ${s.message}
`),a.usage}};if(process.argv[1]&&import.meta.url===f(g(process.argv[1])).href){let n=[];for await(let t of process.stdin)n.push(t);process.exit(b(process.argv.slice(2),Buffer.concat(n).toString("utf8")))}export{a as EXIT,h as check,y as readingsFrom,w as reconcile,b as run,$ as vocabularyRefusal};
